server:
  port: 8080
  # 配置上下文路径
  servlet:
    context-path: /

spring:
  application:
    name: lz-sports-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  security:
    user:
      name: ${SECURITY_USER_NAME:}
      password: ${SECURITY_USER_PASSWORD:}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
      password: ${REDIS_PASSWORD:}
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/lz_sports.sql
      data-locations: classpath:sql/data.sql

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# 兜底图片配置
fallback:
  images:
    urls:
      - https://picui.ogmua.cn/s1/2026/03/15/69b673bcddc3e.webp
      - https://picui.ogmua.cn/s1/2026/03/15/69b673bd3d497.webp
      - https://picui.ogmua.cn/s1/2026/03/15/69b673bd596e8.webp
      - https://picui.ogmua.cn/s1/2026/03/15/69b673bd767bf.webp
      - https://picui.ogmua.cn/s1/2026/03/15/69b673bd895ee.webp
      - https://picui.ogmua.cn/s1/2026/03/15/69b673c56c550.webp

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.lz.common.enums
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Custom Config
jwt:
  key: ${JWT_SECRET}
  expiration: 43200000 # 12 hours

aliyun:
  oss:
    endpoint: ${OSS_ENDPOINT}
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
    bucketName: ${OSS_BUCKET_NAME}

app:
  upload-dir: ${APP_UPLOAD_DIR:uploads}

logging:
  file:
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 5GB
  level:
    com.lz.mapper: debug
